### PR TITLE
Fix CMakeLists.txt File

### PR DESCRIPTION
**Pull request by edenreich**
This pull request is related to #426 

For now I just commented these missing files out, now after running `cmake ..` inside of the build directory it configures the project successfully.

### CODE REVIEW

**Comment by scorninpc** [comment]
have you success compiling simple example on windows?

I have alot errors, but compile phpcpp-common.lib

I need more than that? Because when i try include phpcpp.h, alot errors appear, cause there'nt c++11 for cl compiller, so that's why i dont know if my phpcpp are compilling correctly

I'm stuck

**Comment by edenreich** [comment]
@scorninpc oh that was a long time ago sense I've tried, I will try again perhaps this weekend or the next one and let you know if it is successfully compiling. As I remember I did find some missing files that probably were not added / updated on CMakeLists.txt, but were modified on the source code.

**Comment by scorninpc** [comment]
Thank you alot @edenreich. 

Most errors are syntax, native types missing, which I don't understand why. I think this problem is some configuration or version that I am using. As I am completely unaware of windows, I was lost where to start. No hurry, I await your tests. If you need, I have merged the php 7.4 and your cmakelist branches here https://github.com/scorninpc/PHP-CPP

**Comment by edenreich** [comment]
@scorninpc hey can you describe what kind of errors do you get when compiling ?

**Comment by scorninpc** [comment]
Hello Eden

I have sintax or type errors, like that:

Look start build

image

And start errors (sorry for PT-BR compile errors, but it's easy)

image

As you can see, the errors are sintax erros, like ; missing.

I've compiled on linux using C17 like cl compiller, and it's work fine

**Pull request merged**
